Add quotes to milestone in case title contains spaces
weierophinney/changelog_generator pull request #17
Opened 2016-11-18 15:10 UTC by asgrim

Discovered a bug where if the milestone title contains a space (e.g. `1.0.0 (initial release)`), the search fails to find any issues. Simple fix here is to always quote the `milestone`, I see no adverse affects with milestones that do not contain spaces (e.g. `1.0.0`).

2016-11-19 15:26 UTC, Ocramius requested changes

2016-11-19 15:26 UTC, Ocramius commented on changelog_generator.php
> +        'milestone:"' . $milestonePayload['title'] . '"'
Since it was brought to the table - what happens with a `"` in the milestone?

2016-11-21 09:25 UTC, asgrim commented on changelog_generator.php
> +        'milestone:"' . $milestonePayload['title'] . '"'
Good catch, I've added a straightforward replacement of `"` to `\"` which is all that is required. I looked into using `addslashes()` but it is only `"` that must be escaped (and escaping others such as ``'` will result in the search failing.

2017-02-22 20:32 UTC, merged

2017-02-22 20:33 UTC, weierophinney commented
Thanks, @asgrim\!